server:
  port: 5000
eureka:
  client:
    service-url:
      defalutzone: http://localhost:8761/eureka/
spring:
  sleuth:
    web:
      client:
        enabled: true #打开sleuth客户端功能
    sampler:
      probability: 1.0 #将采样比设置为1，全部采样，默认为0.1
  zipkin:
    base-url: http://localhost:9411/ #指定链路追踪服务地址
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders:
    blogservice:
      path: /blogapi/**
      serviceId: blog-service
      sensitiveHeaders:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  file: "logs/gateway-service.log"
